//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twinkle.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twinkle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Add... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddModal {
            get {
                return ResourceManager.GetString("AddModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonNewTweet {
            get {
                return ResourceManager.GetString("ButtonNewTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open In Web Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOpenInBrowser {
            get {
                return ResourceManager.GetString("ButtonOpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate Clockwise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRotateClockwise {
            get {
                return ResourceManager.GetString("ButtonRotateClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate Counterclockwise に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRotateCounterClockwise {
            get {
                return ResourceManager.GetString("ButtonRotateCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Templates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTemplates {
            get {
                return ResourceManager.GetString("ButtonTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTweet {
            get {
                return ResourceManager.GetString("ButtonTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDialogFilterImage {
            get {
                return ResourceManager.GetString("FileDialogFilterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Document (*.txt)|*.txt|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDialogFilterTweet {
            get {
                return ResourceManager.GetString("FileDialogFilterTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterAllFiles {
            get {
                return ResourceManager.GetString("FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter Script: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFilterScript {
            get {
                return ResourceManager.GetString("LabelFilterScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginConfirm {
            get {
                return ResourceManager.GetString("LoginConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consumer Key: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginConsumerKey {
            get {
                return ResourceManager.GetString("LoginConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consumer Secret: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginConsumerSecret {
            get {
                return ResourceManager.GetString("LoginConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PIN Code: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginPinCode {
            get {
                return ResourceManager.GetString("LoginPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginStartAuthentication {
            get {
                return ResourceManager.GetString("LoginStartAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step 1: Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginStep1 {
            get {
                return ResourceManager.GetString("LoginStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step 2: Enter a PIN Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginStep2 {
            get {
                return ResourceManager.GetString("LoginStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use custom Consumer Key / Consumer Secret に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginUseCustomKey {
            get {
                return ResourceManager.GetString("LoginUseCustomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About Twinkle for Windows... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuAccounts {
            get {
                return ResourceManager.GetString("MenuAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuAdd {
            get {
                return ResourceManager.GetString("MenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Connect To Stream に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuConnectToStream {
            get {
                return ResourceManager.GetString("MenuConnectToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Disconnect From Stream に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuDisconnectFromStream {
            get {
                return ResourceManager.GetString("MenuDisconnectFromStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get _Favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGetFavorites {
            get {
                return ResourceManager.GetString("MenuGetFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get _Home Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGetHomeTimeline {
            get {
                return ResourceManager.GetString("MenuGetHomeTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get _Mentions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGetMentions {
            get {
                return ResourceManager.GetString("MenuGetMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get M_y Tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGetMyTweets {
            get {
                return ResourceManager.GetString("MenuGetMyTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuImageClipboard {
            get {
                return ResourceManager.GetString("MenuImageClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuImageFile {
            get {
                return ResourceManager.GetString("MenuImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch _Snipping Tool... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuImageLaunchSnippingTool {
            get {
                return ResourceManager.GetString("MenuImageLaunchSnippingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Tweet... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuNewTweet {
            get {
                return ResourceManager.GetString("MenuNewTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuNoAccounts {
            get {
                return ResourceManager.GetString("MenuNoAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected from stream に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuNotStreaming {
            get {
                return ResourceManager.GetString("MenuNotStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Options... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuQuit {
            get {
                return ResourceManager.GetString("MenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Streaming... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuStreamingNow {
            get {
                return ResourceManager.GetString("MenuStreamingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Timelines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTimelines {
            get {
                return ResourceManager.GetString("MenuTimelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T_ools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An account has been registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAccountRegeistered {
            get {
                return ResourceManager.GetString("MessageAccountRegeistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This account has already been registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageAlreadyRegistered {
            get {
                return ResourceManager.GetString("MessageAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application has started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageApplicationStart {
            get {
                return ResourceManager.GetString("MessageApplicationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed receiving latest {0} tweets in favorites. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCompleteFavoriteReceiving {
            get {
                return ResourceManager.GetString("MessageCompleteFavoriteReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed receiving latest {0} tweets in home timeline. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCompleteHomeReceiving {
            get {
                return ResourceManager.GetString("MessageCompleteHomeReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed receiving latest {0} tweets in mentions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCompleteMentionsReceiving {
            get {
                return ResourceManager.GetString("MessageCompleteMentionsReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed receiving latest {0} tweets in my account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageCompleteMyTweetReceiving {
            get {
                return ResourceManager.GetString("MessageCompleteMyTweetReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} has deleted a tweet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageDeletedTweet {
            get {
                return ResourceManager.GetString("MessageDeletedTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web browser will open. Authorize the application and then enter a PIN Code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageEnterPinCode {
            get {
                return ResourceManager.GetString("MessageEnterPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} favorited your tweet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFavorited {
            get {
                return ResourceManager.GetString("MessageFavorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image has been saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageImageSaved {
            get {
                return ResourceManager.GetString("MessageImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no registered accounts. Click here to view details. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNoAccounts {
            get {
                return ResourceManager.GetString("MessageNoAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To register a new account, click [Accounts]-&gt;[Add...]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageNoAccountsDetail {
            get {
                return ResourceManager.GetString("MessageNoAccountsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please press &quot;Start Authentication.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessagePressStartAuthentication {
            get {
                return ResourceManager.GetString("MessagePressStartAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending tweet... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSendingTweet {
            get {
                return ResourceManager.GetString("MessageSendingTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet has been sent. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSentTweet {
            get {
                return ResourceManager.GetString("MessageSentTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication has started... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStartAuthentication {
            get {
                return ResourceManager.GetString("MessageStartAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet has been saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageTweetSaved {
            get {
                return ResourceManager.GetString("MessageTweetSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @{0} unfavorited your tweet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageUnfavorited {
            get {
                return ResourceManager.GetString("MessageUnfavorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploading ({0} of {1})... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageUploading {
            get {
                return ResourceManager.GetString("MessageUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying PIN Code... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageVerifyingPinCode {
            get {
                return ResourceManager.GetString("MessageVerifyingPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accounts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsAccounts {
            get {
                return ResourceManager.GetString("OptionsAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect To Stream When Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsAccountsConnectToStreamWhenStart {
            get {
                return ResourceManager.GetString("OptionsAccountsConnectToStreamWhenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Favorites When Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsAccountsLoadFavoritesWhenStart {
            get {
                return ResourceManager.GetString("OptionsAccountsLoadFavoritesWhenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Home Timeline When Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsAccountsLoadHomeTimelineWhenStart {
            get {
                return ResourceManager.GetString("OptionsAccountsLoadHomeTimelineWhenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Mentions When Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsAccountsLoadMentionsWhenStart {
            get {
                return ResourceManager.GetString("OptionsAccountsLoadMentionsWhenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get My Tweets When Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsAccountsLoadMyTweetsWhenStart {
            get {
                return ResourceManager.GetString("OptionsAccountsLoadMyTweetsWhenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Behavior に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsBehavior {
            get {
                return ResourceManager.GetString("OptionsBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Tweet In Specific Folder Automatically When Deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsBehaviorAutoTweetSave {
            get {
                return ResourceManager.GetString("OptionsBehaviorAutoTweetSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Save Folder: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsBehaviorImageSaveFolder {
            get {
                return ResourceManager.GetString("OptionsBehaviorImageSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Asks When Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsBehaviorImageSaveFolderAsk {
            get {
                return ResourceManager.GetString("OptionsBehaviorImageSaveFolderAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsBehaviorImageSaveFolderSpecify {
            get {
                return ResourceManager.GetString("OptionsBehaviorImageSaveFolderSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet Save Folder: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsBehaviorTweetSaveFolder {
            get {
                return ResourceManager.GetString("OptionsBehaviorTweetSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Asks When Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsBehaviorTweetSaveFolderAsk {
            get {
                return ResourceManager.GetString("OptionsBehaviorTweetSaveFolderAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsBehaviorTweetSaveFolderSpecify {
            get {
                return ResourceManager.GetString("OptionsBehaviorTweetSaveFolderSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsGeneral {
            get {
                return ResourceManager.GetString("OptionsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsGeneralLanguage {
            get {
                return ResourceManager.GetString("OptionsGeneralLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsView {
            get {
                return ResourceManager.GetString("OptionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Size: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsViewTextSize {
            get {
                return ResourceManager.GetString("OptionsViewTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline Width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OptionsViewTimelineWidth {
            get {
                return ResourceManager.GetString("OptionsViewTimelineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}d に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeDay {
            get {
                return ResourceManager.GetString("TimeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}h に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeHour {
            get {
                return ResourceManager.GetString("TimeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}m に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeMinute {
            get {
                return ResourceManager.GetString("TimeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeNow {
            get {
                return ResourceManager.GetString("TimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeSecond {
            get {
                return ResourceManager.GetString("TimeSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open In Web Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TweetMenuOpenInBrowser {
            get {
                return ResourceManager.GetString("TweetMenuOpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TweetMenuSaveTweet {
            get {
                return ResourceManager.GetString("TweetMenuSaveTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Twinkle for Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitleAbout {
            get {
                return ResourceManager.GetString("WindowTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Messages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitleApplicationMessages {
            get {
                return ResourceManager.GetString("WindowTitleApplicationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitleLogin {
            get {
                return ResourceManager.GetString("WindowTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitleNewTweet {
            get {
                return ResourceManager.GetString("WindowTitleNewTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitleOptions {
            get {
                return ResourceManager.GetString("WindowTitleOptions", resourceCulture);
            }
        }
    }
}
